[package]
name = "hotelca"
version = "0.1.0"
authors = ["Marco Chomut <marco.chomut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy = "0.0.302"
error-chain = "0.12.2"
